### ISSUE TITLE
App does not load on OSX 10.10.4 

### ISSUE THREAD

**Issue by OR13** [AurousGroup/Feature-Tracker#25]
This download link: https://aurous.me/downloads/Aurous.dmg

Does not appear to work. The dmg mounts, but the app does nothing when clicked.

I'm happy to debug if I can.

**Comment by dmxt** [comment]
Do you have Java installed?

**Comment by dmxt** [comment]
This does not belong in Feature-Tracker, please post it in Bug-Tracker.
